version: '3'

services:
  python:
    image: python:3.6
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: testing
    volumes:
      - .:/testing
    ports:
      - "8000:8000"
    depends_on:
      - db